name: Merge Upstream Branches

on:
  schedule:
    - cron: '0 12 * * *'  # Run daily at noon (your server's time)

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: List Upstream Branches
        run: |
          git branch -r | grep -v '\->' | sed "s,\x1B\[[0-9;]*[a-zA-Z],,g"

      - name: Verify Upstream Branches
        run: |
          for branch in ${{ steps.list-upstream-branches.outputs }}; do
            git ls-remote https://github.com/ppfeufer/adguard-filter-list "$branch" &> /dev/null
            if [[ $? -ne 0 ]]; then
              echo "Warning: Branch '$branch' not found on remote."
            fi
          done

      - name: Add and Track Remote Branches
        run: |
          for branch in ${{ steps.list-upstream-branches.outputs }}; do
            git branch --track "origin/$branch" "https://github.com/ppfeufer/adguard-filter-list/$branch"
          done

      - name: Fetch Latest Changes
        run: git fetch --all

      - name: Merge Upstream Branches (Add checks if desired)
        run: |
          for branch in ${{ steps.list-upstream-branches.outputs }}; do
            git checkout "origin/$branch"
            git merge "main"  # Replace "main" with your main branch name if different
            # Add checks here to ensure successful merge (e.g., no conflicts)
            # If checks fail, consider notifying maintainers or skipping the merge.
          done
